name: "Technical Architecture Design"
version: "1.0.0"
category: "solutioning"
description: "Design comprehensive technical architecture for projects"

inputs:
  - name: "project_context"
    description: "Project goals, requirements, and constraints"
    required: true
  - name: "code_examples"
    description: "Example usage or API design"
    required: false
  - name: "scale_requirements"
    description: "Expected scale, performance, and usage patterns"
    required: false

phases:
  - id: "analyze"
    name: "Requirements Analysis"
    steps:
      - action: "Extract functional requirements from examples"
        output: "functional_requirements"
      - action: "Identify non-functional requirements (performance, security, scalability)"
        output: "non_functional_requirements"
      - action: "List technical constraints and dependencies"
        output: "constraints"

  - id: "design"
    name: "Architecture Design"
    steps:
      - action: "Design system components and their responsibilities"
        output: "component_diagram"
      - action: "Define data flow and communication patterns"
        output: "data_flow"
      - action: "Choose technology stack and justify decisions"
        output: "tech_stack"
      - action: "Design API contracts and interfaces"
        output: "api_design"

  - id: "implementation_plan"
    name: "Implementation Planning"
    steps:
      - action: "Define project structure (folders, modules, packages)"
        output: "project_structure"
      - action: "Identify third-party dependencies"
        output: "dependencies"
      - action: "Create implementation roadmap with phases"
        output: "roadmap"

  - id: "quality"
    name: "Quality & Operations"
    steps:
      - action: "Design testing strategy (unit, integration, e2e)"
        output: "testing_strategy"
      - action: "Plan deployment and distribution approach"
        output: "deployment_plan"
      - action: "Define monitoring and error handling strategy"
        output: "operations_plan"

outputs:
  - name: "architecture_document"
    description: "Comprehensive technical architecture document"
    format: "markdown"
  - name: "implementation_guide"
    description: "Step-by-step implementation guide"
    format: "markdown"

agent: "Winston"  # The architect agent
